# -*- coding: utf-8 -*-
"""etl_ia_generativa_dio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Cw9YfmUgfnKGPxvvsZI0Q78Jyg46qRx
"""

import pandas as pd
import google.generativeai as genai
from google.colab import userdata

GOOGLE_API_KEY = userdata.get('gemini_api')
genai.configure(api_key=GOOGLE_API_KEY)
gemini_model = genai.GenerativeModel('gemini-3-flash-preview')

df = pd.read_csv('clients.csv', sep=';')
users = df.to_dict(orient='records')

def generate_ai_news(user):
    name = user['name']
    imc = user['imc']

    # Classificação do IMC
    if imc < 18.5:
        categoria = "baixo peso"
    elif imc < 25:
        categoria = "peso normal"
    elif imc < 30:
        categoria = "sobrepeso"
    else:
        categoria = "obesidade"

    prompt = (
        "Você é um especialista em saúde e IMC. "
        f"O usuário {name} tem IMC {imc} ({categoria}). Gere uma mensagem motivacional dando dicas como chegar no IMC ideal de até 100 caracteres."
    )

    response = gemini_model.generate_content(prompt)

    return response.text.strip()

for user in users:
    news = generate_ai_news(user)
    user['news'] = [{"description": news}]
    print(f"{user['name']}: {news}")